---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - konnektr.io
  resources:
  - databasequeryresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - konnektr.io
  resources:
  - databasequeryresources/finalizers
  verbs:
  - update
- apiGroups:
  - konnektr.io
  resources:
  - databasequeryresources/status
  verbs:
  - get
  - patch
  - update
